services:
  oauth-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - "8080:8080"
    environment:
      JSON_CONFIG_PATH: /config/mock-oauth2-config.json
      SERVER_PORT: "8080"
    volumes:
      - ./oauth-config:/config
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/default/.well-known/openid-configuration"]
      interval: 5s
      timeout: 3s
      retries: 10
